### PR TITLE
Joannfeng/update edit button url

### PR DESCRIPTION
**Pull request by joannfeng**

### CODE REVIEW

**Comment by BoPeng** [comment]
The updated files still have `8080`, right? You can use a text editor to check.

**Comment by BoPeng** [comment]
Also, it has conflicts so you will need to update to the master before generating another PR.

**Comment by joannfeng** [comment]
Okay, I will update to the master and retry. I'm not sure what you mean by 8080. I thought I was to remove :8000 from the url, and the most recent PR ( #96 ) appears to reflect that.

**Comment by BoPeng** [comment]
> I'm not sure what you mean by 8080.

Yeah, `8000`, people use `8000`, `8888`, `8080` for similar things... so it is easy to get confused.

**Comment by joannfeng** [comment]
Closing in favor of https://github.com/vatlab/sos-docs/pull/97

**Pull request closed without merging**
